name: Test Python Functions
on:
  pull_request:
    paths-ignore:
      - code/python
      - .github/workflows

jobs:
  Test-Python:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test required"'
  Lint-Python:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No linting required"'
