# Run secret-dependent integration tests only if trusted PR, or after
# user with write permissions has commented /ok-to-test on a (fork-based) pull request

on:
  pull_request:
  repository_dispatch:
    types: [ok-to-test-command]

name: Integration tests

jobs:
  # Branch-based pull request
  integration-test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_CLI_CONFIG_FILE: /home/runner/work/terraform-snowflake-playground/terraform-snowflake-playground/src/testing/.terraformrc
      TF_VAR_snowflake_rsa_key_path: /tmp/snowflake.p8
      TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER_NAME }}
      TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
      TF_VAR_snowflake_region: ${{ secrets.SNOWFLAKE_REGION }}
    permissions:
      pull-requests: write
      checks: write
    if: | # source is trusted pr OR ok-to-test
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository
      ) || (
        github.event_name == 'repository_dispatch' &&
        github.event.client_payload.slash_command.args.named.sha != '' &&
        contains(
          github.event.client_payload.pull_request.head.sha,
          github.event.client_payload.slash_command.args.named.sha
        )
      )
    steps:
      - name: Checkout Playground Source Code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Cache Terraform Provider
        uses: actions/cache@v3
        id: cache-sf-tf-provider
        with:
          path: tf_provider/terraform-provider-snowflake
          key: ${{ runner.os }}-sf-tf-provider

      - name: Install go
        if: ${{ steps.cache-sf-tf-provider.outputs.cache-hit != 'true' }}
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Checkout Updated Terraform Provider
        if: ${{ steps.cache-sf-tf-provider.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          repository: 'badge/terraform-provider-snowflake'
          path: tf_provider

      - name: Get Go Dependencies
        if: ${{ steps.cache-sf-tf-provider.outputs.cache-hit != 'true' }}
        working-directory: tf_provider/
        run: go get

      - name: Build Provider
        if: ${{ steps.cache-sf-tf-provider.outputs.cache-hit != 'true' }}
        working-directory: tf_provider/
        run: go build

      - name: Init Terraform for Testing
        working-directory: src/testing/
        run: terraform init

      - name: Save Snowflake RSA Key
        run: echo ${{ secrets.SNOWFLAKE_RSA_KEY }} | base64 -d > /tmp/snowflake.p8
        shell: bash

      - name: Deploy Test Configuration
        working-directory: src/testing/
        run: terraform apply -auto-approve

    # TODO: <insert integration tests needing secrets>
      - run: |
          echo "Integration tests... success! ;-)"

      # Update check run called "integration-fork"
      - uses: actions/github-script@v6
        id: update-check-run
        if: | # source is ok-to-test
          (
            github.event_name == 'repository_dispatch' &&
            github.event.client_payload.slash_command.args.named.sha != '' &&
            contains(
              github.event.client_payload.pull_request.head.sha,
              github.event.client_payload.slash_command.args.named.sha
            )
          )
        env:
          number: ${{ github.event.client_payload.pull_request.number }}
          job: ${{ github.job }}
          # Conveniently, job.status maps to
          # https://developer.github.com/v3/checks/runs/#update-a-check-run
          conclusion: ${{ job.status }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: process.env.number
            });
            const ref = pull.head.sha;
            const { data: checks } = await github.rest.checks.listForRef({
              ...context.repo,
              ref
            });
            const check = checks.check_runs.filter(c => c.name === process.env.job);
            const { data: result } = await github.rest.checks.update({
              ...context.repo,
              check_run_id: check[0].id,
              status: 'completed',
              conclusion: process.env.conclusion
            });
            return result;
