name: Test Python Functions

on: [push]

jobs:
    Test-Normalizing-Procedure-Names:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.9
            - name: Install poetry
              run: pip install poetry
            - name: Install testing environment
              working-directory: playground_terraform/code
              run: |
                poetry install
            - name: Run tests
              working-directory: playground_terraform/code
              run: poetry run pytest
                